V2 Linter API support
AtomLinter/linter-bailey pull request #11
Opened 2019-03-04 21:21 UTC by vzamanillo

Fixes #8 
Plus specs and CI.

2019-03-05 17:52 UTC, Arcanemagus requested changes
I've enabled CircleCI here as well, so the next commit should trigger a build.

2019-03-05 17:52 UTC, Arcanemagus commented on lib/init.js
> +              severity: levelMapping[e.inner.name],
What happens if it's not one of the three mappings you have defined? The `Set` or other approaches you have used elsewhere should work fine here.

2019-03-05 17:52 UTC, Arcanemagus commented on lib/init.js
> +      /* eslint-disable no-console */
```suggestion
      // eslint-disable-next-line no-console
```

2019-03-05 17:52 UTC, Arcanemagus commented on lib/init.js
> +      /* eslint-enable no-console */
```suggestion
```

2019-03-13 16:34 UTC, Arcanemagus approved these changes
Thanks!

2019-03-13 16:37 UTC, merged

2019-03-13 16:40 UTC, Arcanemagus commented
Hmmm, looks like something happened with the beta branch of Atom to break the specs.

2019-03-14 12:35 UTC, vzamanillo commented
> Hmmm, looks like something happened with the beta branch of Atom to break the specs.

Yep, `Failed to load package 'language-bailey'`

2019-03-14 19:12 UTC, Arcanemagus commented
Whoops, forgot to comment back here:

Filed as https://github.com/atom/atom/issues/18983 and fixed in https://github.com/atom/atom/pull/18984, since it's breaking existing packages it should be included in the next beta release 😉.